#kanagawa-dragon
icons:
  cursor: '⤙ '
  task_new: ''
  task_in_progress: ''
  task_hold: ''
  task_done: ''
  topic_icon_left: '' #    
  topic_icon_right: '' #   
  sub_task_middle: '├─'
  sub_task_end: '╰─'
colors:
  bat_color_sheme: 'base16-256'
  header_color: '#717C7C'
  footer_color: '#727169'
  border_color: '#49443C'
  task_topic_color_new_fg: '#C8C093'
  task_topic_color_in_progress_fg: '#1F1F28'
  task_topic_color_hold_fg: '#1F1F28'
  task_topic_color_done_fg: '#C8C093'
  task_topic_color_new_bg: '#49443C'
  task_topic_color_in_progress_bg: '#76946A'
  task_topic_color_hold_bg: '#DCA561'
  task_topic_color_done_bg: '#2B3328'
  task_text_color: '#DCD7BA'
  task_text_color_done: '#49443C'
  task_date_color: '#727169'
  task_duration_color: '#7f849c'
  icon_new_color: '#49443C'
  icon_progress_color: '#76946A'
  icon_hold_color: '#DCA561'
  icon_done_color: '#2B3328'
object_type:
  border_type: 'rounded' # rounded, double, thick, quadrant
